# A demo CRD for the Kopf example operators.
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: iotdbreleases.jfeinauer.dev
spec:
  scope: Namespaced
  group: jfeinauer.dev
  names:
    kind: IoTDBRelease
    plural: iotdbreleases
    singular: iotdbrelease
    shortNames:
      - iotdb
      - iotdbs
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                adminPassword:
                  type: string
                image:
                  type: string
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true

