apiVersion: apps/v1
kind: Deployment
metadata:
  name: iotdb-operator
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: iotdb-operator
  template:
    metadata:
      labels:
        application: iotdb-operator
    spec:
      serviceAccountName: iotdb-operator-account
      containers:
        - name: the-only-one
          image: jfeinauer/iotdb-operator
          imagePullPolicy: Always
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: iotdb-operator-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iotdb-operator
rules:
  - apiGroups: ["apps", "", "batch", "jfeinauer.dev"]
    #  resources: ["pods", "deployments", "statefulsets", "services"]
    resources: ["*"]
    verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: iotdb-operator
subjects:
  - kind: ServiceAccount
    name: iotdb-operator-account
    namespace: iotdb-demo
roleRef:
  kind: ClusterRole
  name: iotdb-operator
  apiGroup: rbac.authorization.k8s.io
