apiVersion: batch/v1
kind: Job
metadata:
  name: {name}-init
spec:
  template:
    spec:
      containers:
        - name: portal
          image: jfeinauer/iotdb-cloud:latest
          imagePullPolicy: Always
          args:
            - "iotdb-setup"
          env:
            - name: IOTDB_PASSWORD
              value: {admin_password}
            - name: IOTDB_HOST
              value: {name}-service
      restartPolicy: Never
  backoffLimit: 100